[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "outside tissue father logic often muffin hazard decade secret news sea inform response various budget market myself okay decline display toilet stove lamp oven"
